version: 0.0
Resources:
  - myPythonApp:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:iam::833062305957:role/ecsTaskExecutionRole
        LoadBalancerInfo:
          ContainerName: blue
          ContainerPort: 5000
