version: 0.0
Resources:
  - myPythonApp:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:833062305957:task-definition/Demo-task:2
        LoadBalancerInfo:
          ContainerName: blue
          ContainerPort: 5000
